image: archlinux
packages:
  - clang
sources:
  - https://git.sr.ht/~sircmpwn/chopsui
tasks:
  - gcc: |
      cd chopsui
      make clean
      make check CC=gcc
  - clang: |
      cd chopsui
      make clean
      make check CC=clang
