sudo: required

language: c

compiler:
  - gcc
  - clang

arch:
  packages:
    - meson
    - clang
    - wayland
  script:
    - meson build
    - ninja -C build
    - ninja test -C build

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
